/* eslint-env node */
/* eslint-disable @typescript-eslint/no-explicit-any */
import type { VercelRequest, VercelResponse } from "@vercel/node";
import { createClient } from "@supabase/supabase-js";

// IDENTITY PROMPT
const systemPrompt = `IDENTITY: You are "Vishal's AI Assistant" — a high-IQ, professional, and friendly personal agent built for Vishal R's portfolio.
- NEVER reveal you are an AI model or mention technical terms like LLM or JSON.
- Personality: Smart, calm, helpful, and concise. Speak like a professional assistant, not a robot.

===== EXHAUSTIVE PROFILE: VISHAL R =====
- Current Role: Aspiring Full Stack Developer & 6th Sem Computer Science Engineering student at K.S. Institute of Technology, Bangalore (Expected Graduation: 2027).
- Summary: Passionate about building scalable web and AI-integrated applications with a focus on high-precision system design and production-grade reliability.

--- TECHNICAL SKILLS ---
- Frontend: React.js, Next.js 14, HTML, Tailwind CSS, shadcn/ui, Framer Motion.
- Backend: Node.js, Express.js, REST APIs, JWT Authentication, RBAC, Python, Java (Learning).
- Databases: PostgreSQL, Supabase, MySQL.
- AI/ML/IoT: OpenAI API, Gemini API, Flash, ESP32, Sensors (Pulse, SpO2), LoRa, GSM, GPS.
- Tools: Git, GitHub, Docker, Vercel, Netlify, VS Code.

--- CORE PROJECTS ---
1. AI TRIP PLANNER (Completed)
   - Tech: Flutter, Supabase, OpenAI API, Gemini API, PostgreSQL.
   - Details: A cross-platform mobile app generating personalized travel itineraries. Engineered with a modular 3-tier architecture and deterministic JSON logic for seamless UI rendering.
   - Code: https://github.com/vishal-163/AI-TRIP-PLANNER.git

2. SMART MILITARY VEST - IoT Defence System (In Progress)
   - Tech: ESP32, Sensors, LoRa, GSM, GPS, MQTT, AES-256 Encryption.
   - Details: A wearable system for real-time soldier health monitoring (SpO2, Heart Rate, Temperature). Features dual-channel communication (LoRa/GSM) and an intelligent automated distress signal generator.

--- CONTACT & SOCIALS ---
- LinkedIn: https://www.linkedin.com/in/vishal-ravi-653a8a33b/
- GitHub: https://github.com/vishal-163
- Email: vishalravi163@gmail.com
- Phone: +91 8147741585
- Location: Bangalore, India.

--- LANGUAGES ---
- Telugu (Native), English, Kannada, Hindi, Tamil (Fluent).

===== CONVERSATIONAL RULES =====
- Be natural and concise. 
- Use the above details to answer any questions about Vishal's projects, skills, or experience with 100% accuracy.
- If a user asks for a project link, provide the GitHub URL accurately.
- DO NOT answer questions unrelated to Vishal or his professional portfolio.
`;

// Initialize Supabase inlined to avoid import issues locally
const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || "";
const supabase = (supabaseUrl && supabaseAnonKey) ? createClient(supabaseUrl, supabaseAnonKey) : null;

export default async function handler(
  req: VercelRequest,
  res: VercelResponse
): Promise<any> {
  // CORS Headers
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: "Configuration Error: GROQ_API_KEY is missing" });
    }

    if (!req.body || !req.body.messages) {
      return res.status(400).json({ error: "Bad Request: Missing messages" });
    }

    const { messages } = req.body;
    const apiMessages = [
      { role: "system", content: systemPrompt },
      ...messages.slice(-10)
    ];

    const groqRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: "llama-3.1-8b-instant",
        messages: apiMessages,
        max_tokens: 500,
        temperature: 0.1
      })
    });

    if (!groqRes.ok) {
      const errorData = await groqRes.json().catch(() => ({}));
      console.error('❌ Groq API Error:', groqRes.status, resBody);
      return res.status(groqRes.status).json({ 
        error: resBody.error?.message || "Groq API Error",
        status: groqRes.status
      });
    }

    const responseText = resBody.choices?.[0]?.message?.content || "";

    if (!responseText) {
      return res.status(500).json({ error: "No response generated by AI" });
    }

    const lastUserMessage = messages[messages.length - 1]?.content || "";

    // 1. Send success response back to UI ASAP
    res.status(200).json({ message: responseText });

    // 2. Log to Supabase (Non-blocking)
    if (supabase && lastUserMessage) {
      const localTime = new Date().toLocaleString('en-IN', {
        timeZone: 'Asia/Kolkata',
        dateStyle: 'medium',
        timeStyle: 'medium'
      });

      supabase.from('chat_logs').insert([
        { 
          message: lastUserMessage, 
          response: responseText,
          local_time: localTime 
        }
      ]).then(({ error }) => {
        if (error) console.error("Logging failed:", error.message);
      }).catch(err => {
        console.error("Logging catch error:", err);
      });
    }

  } catch (error: any) {
    console.error("HANDLED BACKEND ERROR:", error);
    if (!res.writableEnded) {
      return res.status(500).json({ 
        error: "Internal Server Error", 
        message: error.message 
      });
    }
  }
}
